# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy the project files
COPY . /app

# Install build dependencies
RUN pip install --upgrade pip \
    && pip install --no-cache-dir hatchling

# Install project dependencies
RUN pip install --no-cache-dir .

# Expose a port if needed (optional)
# ENV PORT=8000

# Command to start the MCP server
CMD ["python", "-m", "mcp_server_calculator"]
